version: '2'
services:
  master:
    container_name: master
    #hostname: master
    ports:
     - "8089:8089"
     - "5557:5557"
     - "5558:5558"
    logging:
      driver: awslogs
      options: 
        awslogs-group: nuage-studio
        awslogs-region: eu-west-1
        awslogs-stream-prefix: locust     
    image: "rmrbest/locust"
    environment:
      ATTACKED_HOST: https://nuage.studio
      LOCUST_MODE: master
      LOCUST_MASTER_BIND_PORT: 5557
      TASK_DELAY: 1000
      QUIET_MODE: "${QUIET_MODE:-false}"     